
package awdl.history;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IServiceAmisco", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IServiceAmisco {


    /**
     * 
     * @param idActor
     * @return
     *     returns awdl.history.ArrayOfPlayerInfo
     */
    @WebMethod(operationName = "GetActor", action = "http://tempuri.org/IServiceAmisco/GetActor")
    @WebResult(name = "GetActorResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetActor", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetActor")
    @ResponseWrapper(localName = "GetActorResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetActorResponse")
    public ArrayOfPlayerInfo getActor(
        @WebParam(name = "idActor", targetNamespace = "http://tempuri.org/")
        ArrayOfint idActor);

    /**
     * 
     * @param idTeam
     * @param date
     * @return
     *     returns awdl.history.ArrayOfPlayerInfo
     */
    @WebMethod(operationName = "GetTeamActors", action = "http://tempuri.org/IServiceAmisco/GetTeamActors")
    @WebResult(name = "GetTeamActorsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTeamActors", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetTeamActors")
    @ResponseWrapper(localName = "GetTeamActorsResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetTeamActorsResponse")
    public ArrayOfPlayerInfo getTeamActors(
        @WebParam(name = "IdTeam", targetNamespace = "http://tempuri.org/")
        Integer idTeam,
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar date);

    /**
     * 
     * @param idencounter
     * @return
     *     returns awdl.history.ArrayOfPlayerInfo
     */
    @WebMethod(operationName = "GetEncounterActors", action = "http://tempuri.org/IServiceAmisco/GetEncounterActors")
    @WebResult(name = "GetEncounterActorsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetEncounterActors", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetEncounterActors")
    @ResponseWrapper(localName = "GetEncounterActorsResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetEncounterActorsResponse")
    public ArrayOfPlayerInfo getEncounterActors(
        @WebParam(name = "Idencounter", targetNamespace = "http://tempuri.org/")
        Integer idencounter);

    /**
     * 
     * @param idActors
     * @return
     *     returns awdl.history.ArrayOfPhotoInfo
     */
    @WebMethod(operationName = "GetActorPhoto", action = "http://tempuri.org/IServiceAmisco/GetActorPhoto")
    @WebResult(name = "GetActorPhotoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetActorPhoto", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetActorPhoto")
    @ResponseWrapper(localName = "GetActorPhotoResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetActorPhotoResponse")
    public ArrayOfPhotoInfo getActorPhoto(
        @WebParam(name = "IdActors", targetNamespace = "http://tempuri.org/")
        ArrayOfint idActors);

    /**
     * 
     * @param idTeams
     * @return
     *     returns awdl.history.ArrayOfCustomTeam
     */
    @WebMethod(operationName = "GetTeam", action = "http://tempuri.org/IServiceAmisco/GetTeam")
    @WebResult(name = "GetTeamResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTeam", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetTeam")
    @ResponseWrapper(localName = "GetTeamResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetTeamResponse")
    public ArrayOfCustomTeam getTeam(
        @WebParam(name = "idTeams", targetNamespace = "http://tempuri.org/")
        ArrayOfint idTeams);

    /**
     * 
     * @param idTeam
     * @param idSeason
     * @return
     *     returns awdl.history.ArrayOfPhotoInfo
     */
    @WebMethod(operationName = "GetTeamPlayersPhotos", action = "http://tempuri.org/IServiceAmisco/GetTeamPlayersPhotos")
    @WebResult(name = "GetTeamPlayersPhotosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTeamPlayersPhotos", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetTeamPlayersPhotos")
    @ResponseWrapper(localName = "GetTeamPlayersPhotosResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetTeamPlayersPhotosResponse")
    public ArrayOfPhotoInfo getTeamPlayersPhotos(
        @WebParam(name = "IdSeason", targetNamespace = "http://tempuri.org/")
        Integer idSeason,
        @WebParam(name = "IdTeam", targetNamespace = "http://tempuri.org/")
        Integer idTeam);

    /**
     * 
     * @param idTeams
     * @return
     *     returns awdl.history.ArrayOfPhotoInfo
     */
    @WebMethod(operationName = "GetTeamLogo", action = "http://tempuri.org/IServiceAmisco/GetTeamLogo")
    @WebResult(name = "GetTeamLogoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTeamLogo", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetTeamLogo")
    @ResponseWrapper(localName = "GetTeamLogoResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetTeamLogoResponse")
    public ArrayOfPhotoInfo getTeamLogo(
        @WebParam(name = "IdTeams", targetNamespace = "http://tempuri.org/")
        ArrayOfint idTeams);

    /**
     * 
     * @param idSeasons
     * @return
     *     returns awdl.history.ArrayOfSeasonInfo
     */
    @WebMethod(operationName = "GetSeason", action = "http://tempuri.org/IServiceAmisco/GetSeason")
    @WebResult(name = "GetSeasonResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSeason", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetSeason")
    @ResponseWrapper(localName = "GetSeasonResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetSeasonResponse")
    public ArrayOfSeasonInfo getSeason(
        @WebParam(name = "idSeasons", targetNamespace = "http://tempuri.org/")
        ArrayOfint idSeasons);

    /**
     * 
     * @param idCompetition
     * @return
     *     returns awdl.history.ArrayOfSeasonInfo
     */
    @WebMethod(operationName = "GetCompetitionSeasons", action = "http://tempuri.org/IServiceAmisco/GetCompetitionSeasons")
    @WebResult(name = "GetCompetitionSeasonsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCompetitionSeasons", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetCompetitionSeasons")
    @ResponseWrapper(localName = "GetCompetitionSeasonsResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetCompetitionSeasonsResponse")
    public ArrayOfSeasonInfo getCompetitionSeasons(
        @WebParam(name = "idCompetition", targetNamespace = "http://tempuri.org/")
        Integer idCompetition);

    /**
     * 
     * @param idSeason
     * @return
     *     returns awdl.history.ArrayOfPhotoInfo
     */
    @WebMethod(operationName = "GetSeasonPlayersPhotos", action = "http://tempuri.org/IServiceAmisco/GetSeasonPlayersPhotos")
    @WebResult(name = "GetSeasonPlayersPhotosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSeasonPlayersPhotos", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetSeasonPlayersPhotos")
    @ResponseWrapper(localName = "GetSeasonPlayersPhotosResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetSeasonPlayersPhotosResponse")
    public ArrayOfPhotoInfo getSeasonPlayersPhotos(
        @WebParam(name = "IdSeason", targetNamespace = "http://tempuri.org/")
        Integer idSeason);

    /**
     * 
     * @param idSeason
     * @return
     *     returns awdl.history.ArrayOfPhotoInfo
     */
    @WebMethod(operationName = "GetSeasonTeamsLogos", action = "http://tempuri.org/IServiceAmisco/GetSeasonTeamsLogos")
    @WebResult(name = "GetSeasonTeamsLogosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSeasonTeamsLogos", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetSeasonTeamsLogos")
    @ResponseWrapper(localName = "GetSeasonTeamsLogosResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetSeasonTeamsLogosResponse")
    public ArrayOfPhotoInfo getSeasonTeamsLogos(
        @WebParam(name = "IdSeason", targetNamespace = "http://tempuri.org/")
        Integer idSeason);

    /**
     * 
     * @param idCompetitions
     * @return
     *     returns awdl.history.ArrayOfCompetitionInfo
     */
    @WebMethod(operationName = "GetCompetition", action = "http://tempuri.org/IServiceAmisco/GetCompetition")
    @WebResult(name = "GetCompetitionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCompetition", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetCompetition")
    @ResponseWrapper(localName = "GetCompetitionResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetCompetitionResponse")
    public ArrayOfCompetitionInfo getCompetition(
        @WebParam(name = "idCompetitions", targetNamespace = "http://tempuri.org/")
        ArrayOfint idCompetitions);

    /**
     * 
     * @param idPitchs
     * @return
     *     returns awdl.history.ArrayOfPitchInfo
     */
    @WebMethod(operationName = "GetPitch", action = "http://tempuri.org/IServiceAmisco/GetPitch")
    @WebResult(name = "GetPitchResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPitch", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetPitch")
    @ResponseWrapper(localName = "GetPitchResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetPitchResponse")
    public ArrayOfPitchInfo getPitch(
        @WebParam(name = "idPitchs", targetNamespace = "http://tempuri.org/")
        ArrayOfint idPitchs);

    /**
     * 
     * @param idLanguage
     * @return
     *     returns awdl.history.ArrayOfProfessionInfo
     */
    @WebMethod(operationName = "GetProfessions", action = "http://tempuri.org/IServiceAmisco/GetProfessions")
    @WebResult(name = "GetProfessionsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetProfessions", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetProfessions")
    @ResponseWrapper(localName = "GetProfessionsResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetProfessionsResponse")
    public ArrayOfProfessionInfo getProfessions(
        @WebParam(name = "IdLanguage", targetNamespace = "http://tempuri.org/")
        List<String> idLanguage);

    /**
     * 
     * @param idLanguage
     * @return
     *     returns awdl.history.ArrayOfUnitInfo
     */
    @WebMethod(operationName = "GetUnits", action = "http://tempuri.org/IServiceAmisco/GetUnits")
    @WebResult(name = "GetUnitsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetUnits", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetUnits")
    @ResponseWrapper(localName = "GetUnitsResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetUnitsResponse")
    public ArrayOfUnitInfo getUnits(
        @WebParam(name = "IdLanguage", targetNamespace = "http://tempuri.org/")
        List<String> idLanguage);

    /**
     * 
     * @return
     *     returns awdl.history.ArrayOfTextCategoryInfo
     */
    @WebMethod(operationName = "GetTextCategories", action = "http://tempuri.org/IServiceAmisco/GetTextCategories")
    @WebResult(name = "GetTextCategoriesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTextCategories", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetTextCategories")
    @ResponseWrapper(localName = "GetTextCategoriesResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetTextCategoriesResponse")
    public ArrayOfTextCategoryInfo getTextCategories();

    /**
     * 
     * @param idTextCategory
     * @param idTexts
     * @param idLanguage
     * @return
     *     returns awdl.history.ArrayOfTextInfo
     */
    @WebMethod(operationName = "GetTexts", action = "http://tempuri.org/IServiceAmisco/GetTexts")
    @WebResult(name = "GetTextsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTexts", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetTexts")
    @ResponseWrapper(localName = "GetTextsResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetTextsResponse")
    public ArrayOfTextInfo getTexts(
        @WebParam(name = "IdTexts", targetNamespace = "http://tempuri.org/")
        ArrayOfint idTexts,
        @WebParam(name = "IdTextCategory", targetNamespace = "http://tempuri.org/")
        Integer idTextCategory,
        @WebParam(name = "IdLanguage", targetNamespace = "http://tempuri.org/")
        List<String> idLanguage);

    /**
     * 
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "IsReady", action = "http://tempuri.org/IServiceAmisco/IsReady")
    @WebResult(name = "IsReadyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IsReady", targetNamespace = "http://tempuri.org/", className = "awdl.history.IsReady")
    @ResponseWrapper(localName = "IsReadyResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.IsReadyResponse")
    public Boolean isReady();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ServiceVersion", action = "http://tempuri.org/IServiceAmisco/ServiceVersion")
    @WebResult(name = "ServiceVersionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ServiceVersion", targetNamespace = "http://tempuri.org/", className = "awdl.history.ServiceVersion")
    @ResponseWrapper(localName = "ServiceVersionResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.ServiceVersionResponse")
    public String serviceVersion();

    /**
     * 
     * @param idSaison
     * @param idRencontres
     * @param day
     * @return
     *     returns awdl.history.ArrayOfEncounterInfo
     */
    @WebMethod(operationName = "GetEncounters", action = "http://tempuri.org/IServiceAmisco/GetEncounters")
    @WebResult(name = "GetEncountersResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetEncounters", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetEncounters")
    @ResponseWrapper(localName = "GetEncountersResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetEncountersResponse")
    public ArrayOfEncounterInfo getEncounters(
        @WebParam(name = "IdRencontres", targetNamespace = "http://tempuri.org/")
        ArrayOfint idRencontres,
        @WebParam(name = "IdSaison", targetNamespace = "http://tempuri.org/")
        Integer idSaison,
        @WebParam(name = "Day", targetNamespace = "http://tempuri.org/")
        Integer day);

    /**
     * 
     * @param seasonStartYear
     * @param competitionName
     * @param day
     * @param seasonEndYear
     * @return
     *     returns awdl.history.ArrayOfEncounterInfo
     */
    @WebMethod(operationName = "GetEncountersByCompetName", action = "http://tempuri.org/IServiceAmisco/GetEncountersByCompetName")
    @WebResult(name = "GetEncountersByCompetNameResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetEncountersByCompetName", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetEncountersByCompetName")
    @ResponseWrapper(localName = "GetEncountersByCompetNameResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetEncountersByCompetNameResponse")
    public ArrayOfEncounterInfo getEncountersByCompetName(
        @WebParam(name = "CompetitionName", targetNamespace = "http://tempuri.org/")
        String competitionName,
        @WebParam(name = "SeasonStartYear", targetNamespace = "http://tempuri.org/")
        Integer seasonStartYear,
        @WebParam(name = "SeasonEndYear", targetNamespace = "http://tempuri.org/")
        Integer seasonEndYear,
        @WebParam(name = "Day", targetNamespace = "http://tempuri.org/")
        Integer day);

    /**
     * 
     * @param clientIdMatchs
     * @return
     *     returns awdl.history.EncounterInfo
     */
    @WebMethod(operationName = "GetEncountersByIdClients", action = "http://tempuri.org/IServiceAmisco/GetEncountersByIdClients")
    @WebResult(name = "GetEncountersByIdClientsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetEncountersByIdClients", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetEncountersByIdClients")
    @ResponseWrapper(localName = "GetEncountersByIdClientsResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetEncountersByIdClientsResponse")
    public EncounterInfo getEncountersByIdClients(
        @WebParam(name = "ClientIdMatchs", targetNamespace = "http://tempuri.org/")
        Integer clientIdMatchs);

    /**
     * 
     * @param idLanguage
     * @return
     *     returns awdl.history.ArrayOfStatCategInfo
     */
    @WebMethod(operationName = "GetStatCategs", action = "http://tempuri.org/IServiceAmisco/GetStatCategs")
    @WebResult(name = "GetStatCategsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStatCategs", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetStatCategs")
    @ResponseWrapper(localName = "GetStatCategsResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetStatCategsResponse")
    public ArrayOfStatCategInfo getStatCategs(
        @WebParam(name = "IdLanguage", targetNamespace = "http://tempuri.org/")
        List<String> idLanguage);

    /**
     * 
     * @param idLanguage
     * @param idStatCategs
     * @return
     *     returns awdl.history.ArrayOfStatSubCategInfo
     */
    @WebMethod(operationName = "GetStatSubCategs", action = "http://tempuri.org/IServiceAmisco/GetStatSubCategs")
    @WebResult(name = "GetStatSubCategsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStatSubCategs", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetStatSubCategs")
    @ResponseWrapper(localName = "GetStatSubCategsResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetStatSubCategsResponse")
    public ArrayOfStatSubCategInfo getStatSubCategs(
        @WebParam(name = "IdStatCategs", targetNamespace = "http://tempuri.org/")
        ArrayOfint idStatCategs,
        @WebParam(name = "IdLanguage", targetNamespace = "http://tempuri.org/")
        List<String> idLanguage);

    /**
     * 
     * @param idLanguage
     * @param idStatCategs
     * @return
     *     returns awdl.history.ArrayOfStatInfo
     */
    @WebMethod(operationName = "GetStats", action = "http://tempuri.org/IServiceAmisco/GetStats")
    @WebResult(name = "GetStatsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStats", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetStats")
    @ResponseWrapper(localName = "GetStatsResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetStatsResponse")
    public ArrayOfStatInfo getStats(
        @WebParam(name = "IdStatCategs", targetNamespace = "http://tempuri.org/")
        ArrayOfint idStatCategs,
        @WebParam(name = "IdLanguage", targetNamespace = "http://tempuri.org/")
        List<String> idLanguage);

    /**
     * 
     * @param idEncounters
     * @param idTeams
     * @param idStats
     * @return
     *     returns awdl.history.ArrayOfStatValueInfo
     */
    @WebMethod(operationName = "GetStatValueTeam", action = "http://tempuri.org/IServiceAmisco/GetStatValueTeam")
    @WebResult(name = "GetStatValueTeamResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStatValueTeam", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetStatValueTeam")
    @ResponseWrapper(localName = "GetStatValueTeamResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetStatValueTeamResponse")
    public ArrayOfStatValueInfo getStatValueTeam(
        @WebParam(name = "IdTeams", targetNamespace = "http://tempuri.org/")
        ArrayOfint idTeams,
        @WebParam(name = "IdStats", targetNamespace = "http://tempuri.org/")
        ArrayOfint idStats,
        @WebParam(name = "IdEncounters", targetNamespace = "http://tempuri.org/")
        ArrayOfint idEncounters);

    /**
     * 
     * @param idTeams
     * @param idSeasons
     * @param idStats
     * @return
     *     returns awdl.history.ArrayOfStatSeasonValueInfo
     */
    @WebMethod(operationName = "GetStatSeasonValueTeam", action = "http://tempuri.org/IServiceAmisco/GetStatSeasonValueTeam")
    @WebResult(name = "GetStatSeasonValueTeamResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStatSeasonValueTeam", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetStatSeasonValueTeam")
    @ResponseWrapper(localName = "GetStatSeasonValueTeamResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetStatSeasonValueTeamResponse")
    public ArrayOfStatSeasonValueInfo getStatSeasonValueTeam(
        @WebParam(name = "IdTeams", targetNamespace = "http://tempuri.org/")
        ArrayOfint idTeams,
        @WebParam(name = "IdStats", targetNamespace = "http://tempuri.org/")
        ArrayOfint idStats,
        @WebParam(name = "IdSeasons", targetNamespace = "http://tempuri.org/")
        ArrayOfint idSeasons);

    /**
     * 
     * @param idEncounters
     * @param idActors
     * @param idStats
     * @return
     *     returns awdl.history.ArrayOfStatValueInfo
     */
    @WebMethod(operationName = "GetStatValueActor", action = "http://tempuri.org/IServiceAmisco/GetStatValueActor")
    @WebResult(name = "GetStatValueActorResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStatValueActor", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetStatValueActor")
    @ResponseWrapper(localName = "GetStatValueActorResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetStatValueActorResponse")
    public ArrayOfStatValueInfo getStatValueActor(
        @WebParam(name = "IdActors", targetNamespace = "http://tempuri.org/")
        ArrayOfint idActors,
        @WebParam(name = "IdStats", targetNamespace = "http://tempuri.org/")
        ArrayOfint idStats,
        @WebParam(name = "IdEncounters", targetNamespace = "http://tempuri.org/")
        ArrayOfint idEncounters);

    /**
     * 
     * @param idActors
     * @param idSeasons
     * @param idStats
     * @return
     *     returns awdl.history.ArrayOfStatSeasonValueInfo
     */
    @WebMethod(operationName = "GetStatSeasonValueActor", action = "http://tempuri.org/IServiceAmisco/GetStatSeasonValueActor")
    @WebResult(name = "GetStatSeasonValueActorResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStatSeasonValueActor", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetStatSeasonValueActor")
    @ResponseWrapper(localName = "GetStatSeasonValueActorResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetStatSeasonValueActorResponse")
    public ArrayOfStatSeasonValueInfo getStatSeasonValueActor(
        @WebParam(name = "IdActors", targetNamespace = "http://tempuri.org/")
        ArrayOfint idActors,
        @WebParam(name = "IdStats", targetNamespace = "http://tempuri.org/")
        ArrayOfint idStats,
        @WebParam(name = "IdSeasons", targetNamespace = "http://tempuri.org/")
        ArrayOfint idSeasons);

    /**
     * 
     * @param idActors
     * @param idSeasons
     * @param idStats
     * @return
     *     returns awdl.history.ArrayOfStatSeasonActorInfo
     */
    @WebMethod(operationName = "GetStatSeasonActor", action = "http://tempuri.org/IServiceAmisco/GetStatSeasonActor")
    @WebResult(name = "GetStatSeasonActorResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStatSeasonActor", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetStatSeasonActor")
    @ResponseWrapper(localName = "GetStatSeasonActorResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetStatSeasonActorResponse")
    public ArrayOfStatSeasonActorInfo getStatSeasonActor(
        @WebParam(name = "IdActors", targetNamespace = "http://tempuri.org/")
        ArrayOfint idActors,
        @WebParam(name = "IdStats", targetNamespace = "http://tempuri.org/")
        ArrayOfint idStats,
        @WebParam(name = "IdSeasons", targetNamespace = "http://tempuri.org/")
        ArrayOfint idSeasons);

    /**
     * 
     * @param idEncounters
     * @return
     *     returns awdl.history.ArrayOfStatEncounterInfo
     */
    @WebMethod(operationName = "GetStatValueEncounter", action = "http://tempuri.org/IServiceAmisco/GetStatValueEncounter")
    @WebResult(name = "GetStatValueEncounterResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStatValueEncounter", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetStatValueEncounter")
    @ResponseWrapper(localName = "GetStatValueEncounterResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetStatValueEncounterResponse")
    public ArrayOfStatEncounterInfo getStatValueEncounter(
        @WebParam(name = "IdEncounters", targetNamespace = "http://tempuri.org/")
        ArrayOfint idEncounters);

    /**
     * 
     * @param idEncounters
     * @param idActors
     * @return
     *     returns awdl.history.ArrayOfStatActorEncounterInfo
     */
    @WebMethod(operationName = "GetStatValueActorEncounter", action = "http://tempuri.org/IServiceAmisco/GetStatValueActorEncounter")
    @WebResult(name = "GetStatValueActorEncounterResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStatValueActorEncounter", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetStatValueActorEncounter")
    @ResponseWrapper(localName = "GetStatValueActorEncounterResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetStatValueActorEncounterResponse")
    public ArrayOfStatActorEncounterInfo getStatValueActorEncounter(
        @WebParam(name = "IdActors", targetNamespace = "http://tempuri.org/")
        ArrayOfint idActors,
        @WebParam(name = "IdEncounters", targetNamespace = "http://tempuri.org/")
        ArrayOfint idEncounters);

    /**
     * 
     * @param idActors
     * @param idStats
     * @return
     *     returns awdl.history.ArrayOfStatActorTrendInfo
     */
    @WebMethod(operationName = "GetStatValueActorTrend", action = "http://tempuri.org/IServiceAmisco/GetStatValueActorTrend")
    @WebResult(name = "GetStatValueActorTrendResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStatValueActorTrend", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetStatValueActorTrend")
    @ResponseWrapper(localName = "GetStatValueActorTrendResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetStatValueActorTrendResponse")
    public ArrayOfStatActorTrendInfo getStatValueActorTrend(
        @WebParam(name = "IdActors", targetNamespace = "http://tempuri.org/")
        ArrayOfint idActors,
        @WebParam(name = "IdStats", targetNamespace = "http://tempuri.org/")
        ArrayOfint idStats);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetExtracterRanking", action = "http://tempuri.org/IServiceAmisco/GetExtracterRanking")
    @WebResult(name = "GetExtracterRankingResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetExtracterRanking", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetExtracterRanking")
    @ResponseWrapper(localName = "GetExtracterRankingResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetExtracterRankingResponse")
    public String getExtracterRanking();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetExtracterHistoric", action = "http://tempuri.org/IServiceAmisco/GetExtracterHistoric")
    @WebResult(name = "GetExtracterHistoricResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetExtracterHistoric", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetExtracterHistoric")
    @ResponseWrapper(localName = "GetExtracterHistoricResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetExtracterHistoricResponse")
    public String getExtracterHistoric();

    /**
     * 
     * @param idMatch
     * @param idLanguage
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMatchEvents", action = "http://tempuri.org/IServiceAmisco/GetMatchEvents")
    @WebResult(name = "GetMatchEventsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMatchEvents", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetMatchEvents")
    @ResponseWrapper(localName = "GetMatchEventsResponse", targetNamespace = "http://tempuri.org/", className = "awdl.history.GetMatchEventsResponse")
    public String getMatchEvents(
        @WebParam(name = "IdMatch", targetNamespace = "http://tempuri.org/")
        Integer idMatch,
        @WebParam(name = "IdLanguage", targetNamespace = "http://tempuri.org/")
        List<String> idLanguage);

}
