
package awdl.history;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceAmisco", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://portal.amisco.eu:9891/wsdl.xml")
public class ServiceAmisco
    extends Service
{

    private final static URL SERVICEAMISCO_WSDL_LOCATION;
    private final static WebServiceException SERVICEAMISCO_EXCEPTION;
    private final static QName SERVICEAMISCO_QNAME = new QName("http://tempuri.org/", "ServiceAmisco");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://portal.amisco.eu:9891/wsdl.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEAMISCO_WSDL_LOCATION = url;
        SERVICEAMISCO_EXCEPTION = e;
    }

    public ServiceAmisco() {
        super(__getWsdlLocation(), SERVICEAMISCO_QNAME);
    }

    public ServiceAmisco(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEAMISCO_QNAME, features);
    }

    public ServiceAmisco(URL wsdlLocation) {
        super(wsdlLocation, SERVICEAMISCO_QNAME);
    }

    public ServiceAmisco(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEAMISCO_QNAME, features);
    }

    public ServiceAmisco(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceAmisco(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IServiceAmisco
     */
    @WebEndpoint(name = "BasicHttpBinding_IServiceAmisco")
    public IServiceAmisco getBasicHttpBindingIServiceAmisco() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IServiceAmisco"), IServiceAmisco.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServiceAmisco
     */
    @WebEndpoint(name = "BasicHttpBinding_IServiceAmisco")
    public IServiceAmisco getBasicHttpBindingIServiceAmisco(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IServiceAmisco"), IServiceAmisco.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEAMISCO_EXCEPTION!= null) {
            throw SERVICEAMISCO_EXCEPTION;
        }
        return SERVICEAMISCO_WSDL_LOCATION;
    }

}
